#!/usr/bin/env node
/**
 * Generates src/logos.ts from logos/*.svg.
 * Usage: node scripts/build-logos.js
 */
const fs = require('fs');
const path = require('path');

const logosDir = path.join(__dirname, '..', 'logos');
const outFile = path.join(__dirname, '..', 'src', 'logos.ts');

const files = fs
  .readdirSync(logosDir)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const entries = [];
for (const file of files) {
  const code = path.basename(file, '.svg');
  const svg = fs.readFileSync(path.join(logosDir, file), 'utf8').trim();
  if (!svg.startsWith('<svg')) {
    throw new Error(`${file}: does not start with <svg`);
  }
  if (!svg.includes('viewBox="0 0 240 80"')) {
    throw new Error(`${file}: missing viewBox="0 0 240 80"`);
  }
  entries.push(`  ${JSON.stringify(code)}: ${JSON.stringify(svg)},`);
}

const out = `// Generated by scripts/build-logos.ts — do not edit

export const LOGO_VIEWBOX = '0 0 240 80';

export const BANK_LOGOS: Readonly<Record<string, string>> = {
${entries.join('\n')}
};

export const getBankLogo = (bankCode: string): string | undefined =>
  BANK_LOGOS[bankCode];

export const hasBankLogo = (bankCode: string): boolean =>
  bankCode in BANK_LOGOS;
`;

fs.writeFileSync(outFile, out);
console.log(`Wrote ${outFile} with ${entries.length} logos`);
